package ok.suxrob.enums;

public enum Make {
    CHEVROLET, VAZ, LADA, ACURA, ALFA_ROMEO, ANKAI, AUDI, AVIA, BCS, BELARUS, BENTLEY,
    BMW, BUICK, CADILLAC, CAMC, CARMIX, CARSON, CASE, CAT, CHANA, CHIMGAN, CHINA_SCOOTERS,
    CHRYSLER, CHTC, CIMC, CITROIN, CLAAS, DAICIA,
}
