package ok.suxrob.enums.parameters;

public enum BodyColor {  // rang
    BEIGE, BLACK, BLUE, BROWN, BURGUNDY, CREAMY, DARK_BLUE, DARK_BROWN, DARK_GREY, GOLD, GRAY, GREEN, KHAKI,
    LIGHT_GREEN, ORANGE, PINK, RED, SILVER, TURQUOISE, VIOLET, WHITE, YELLOW
}
